# Candace Savonen Apr 2025

name: Testing ottr-preview
on:
  workflow_dispatch:
  pull_request:
    types:
      - opened

jobs:
  rmd-render:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write

    steps:
    - name: Checkout Actions Repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
# update for your user name and branch to test
    - name: Run render for Rmd
      uses: ottrproject/ottr-preview@flatten-directory-paths
      with:
        toggle_website: "rmd"
        root_path: test-rmd

#    - name: Run render for Quarto
#      uses: ottrproject/ottr-preview@flatten-directory-paths
#      with:
#        toggle_website: "quarto"
#        root_path: test-quarto
