# Candace Savonen Apr 2025

name: Testing ottr-preview
on:
  workflow_dispatch:
  pull_request:
    branches: [ main, dev ]

jobs:
  rmd-render:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write

    steps:
    - name: Checkout Actions Repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Run render for Rmd
      uses: ottrproject/ottr-preview@fix-exit-code
      with:
        toggle_website: "rmd"
        root_path: test-rmd

    - name: Run render for Quarto
      uses: ottrproject/ottr-preview@fix-exit-code
      with:
        toggle_website: "quarto"
        root_path: test-quarto
